export const AppConfig = {
	site_name: 'KN8263.GITHUB.IO',
	title: 'KN8263.GITHUB.IO',
	description: '中島功人です。ほぼ自分用のメモサイトです。',
	url: 'https://kn8263.github.io',
	locale: 'ja',
	author: 'Nakashima, Katsuhito',
	copyright: '©Nakashima, Katsuhito Some Rights Reserved',
	pagination_size: 10,
	sidebar_links: [
		{ label: 'このサイトについて', path: '/about' },
		{ label: 'ポートフォリオ', path: '/portfolio' },
		// { label: '連絡フォーム', path: '/contact' },
		// { label: 'Blog', path: '/blog/1' },
	],
	contacts: {
		email: 'kn8263@gmail.com',
		facebook: '',
		telegram: '',
		twitter: '',
		github: 'kn8263',
		rss: '',
		vkontakte: '',
		linkedin: '',
		instagram: '',
		line: '',
		gitlab: '',
		weibo: '',
		codepen: '',
		youtube: '',
		soundcloud: '',
		medium: '',
	},
};
